

--TODO: CREACION DE TABLAS
CREATE TABLE MATRICULA
(
	ID NUMBER(6) NOT NULL,
	CODIGO VARCHAR(40) NOT NULL,
	
	TIPO NUMBER(2) NOT NULL,
	REGISTRO DATE NOT NULL,
	ANULACION DATE NULL,
	NRODOCUMENTO VARCHAR(200) NOT NULL,
	NOMBRE VARCHAR(200) NOT NULL,
	APELLIDO VARCHAR(200) NOT NULL,
	ESTADO NUMBER(1) NOT NULL
);

CREATE TABLE CURSO
(
	ID NUMBER(6) NOT NULL,
	DESCRIPCION VARCHAR(400) NOT NULL,
	CREDITO NUMBER(4) NOT NULL
);

CREATE TABLE SECCION
(
	ID NUMBER(6) NOT NULL,
	CURSOID INT NOT NULL,
	DESCRIPCION VARCHAR(400) NOT NULL,
	VACANTE NUMBER(4) NOT NULL,
	VACANTEUSADA NUMBER(4) NOT NULL,
	ESTADO NUMBER(1) NOT NULL
);

CREATE TABLE MATRICULASECCION
(
	MATRICULAID NUMBER(6) NOT NULL,
	SECCIONID NUMBER(6) NOT NULL
);

--TODO: AGREGAR LLAVES PRIMARIAS
ALTER TABLE MATRICULA ADD CONSTRAINT PK_MATRICULA PRIMARY KEY (ID);
ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (ID);
ALTER TABLE SECCION ADD CONSTRAINT PK_SECCION PRIMARY KEY (ID);
ALTER TABLE MATRICULASECCION ADD CONSTRAINT PK_MATRICULASECCION PRIMARY KEY (MATRICULAID, SECCIONID);


--TODO: CREAR SECUENCIAS
CREATE SEQUENCE MATRICULA_ID_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE CURSO_ID_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;
CREATE SEQUENCE SECCION_ID_SEQ START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE;


--TODO: CREAR DISPARADORES
CREATE TRIGGER MATRICULA_ID_TRG
BEFORE INSERT ON MATRICULA
FOR EACH ROW
BEGIN 
	SELECT MATRICULA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

CREATE TRIGGER CURSO_ID_TRG
BEFORE INSERT ON CURSO
FOR EACH ROW
BEGIN 
	SELECT CURSO_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

CREATE TRIGGER SECCION_ID_TRG
BEFORE INSERT ON SECCION
FOR EACH ROW
BEGIN 
	SELECT SECCION_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

--TODO: REGISTRAR INFORMACIÓN BASE
INSERT INTO CURSO (DESCRIPCION, CREDITO) VALUES ('CURSO 1', 2);
INSERT INTO CURSO (DESCRIPCION, CREDITO) VALUES ('CURSO 2', 2);
INSERT INTO CURSO (DESCRIPCION, CREDITO) VALUES ('CURSO 3', 3);
INSERT INTO CURSO (DESCRIPCION, CREDITO) VALUES ('CURSO 4', 5);
INSERT INTO CURSO (DESCRIPCION, CREDITO) VALUES ('CURSO 5', 6);


INSERT INTO SECCION (CURSOID, DESCRIPCION, VACANTE, VACANTEUSADA, ESTADO) VALUES (1, 'SECCION A', 4, 0, 1);
INSERT INTO SECCION (CURSOID, DESCRIPCION, VACANTE, VACANTEUSADA, ESTADO) VALUES (2, 'SECCION B', 1, 0, 1);
INSERT INTO SECCION (CURSOID, DESCRIPCION, VACANTE, VACANTEUSADA, ESTADO) VALUES (3, 'SECCION B', 3, 0, 1);
INSERT INTO SECCION (CURSOID, DESCRIPCION, VACANTE, VACANTEUSADA, ESTADO) VALUES (4, 'SECCION C', 2, 0, 1);


--TODO: BORRAR TABLAS Y SEQUENCIAS
DROP TABLE SYSTEM.MATRICULASECCION;
DROP TABLE SYSTEM.CURSO;
DROP TABLE SYSTEM.MATRICULA;
DROP TABLE SYSTEM.SECCION;

DROP SEQUENCE SYSTEM.MATRICULA_ID_SEQ;
DROP SEQUENCE SYSTEM.CURSO_ID_SEQ;
DROP SEQUENCE SYSTEM.SECCION_ID_SEQ;